version: '3.1'

services:

  wordpress:
    image: wordpress:php7.4-apache
    container_name: fpay_wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress/html_data:/var/www/html
    # deploy:
    #     resources:
    #         limits:
    #           cpus: 0.50
    #           memory: 512M
    #         reservations:
    #           cpus: 0.25
    #           memory: 128M

  db:
    image: mysql:5.7
    restart: always
    container_name: db_fpay_wordpress
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db/mysql/data:/var/lib/mysql

# volumes:
#   wordpress:
#   db: