version: '3'
services:
  db_service:
    container_name: "${CONTAINER_NAME_DB}"
    env_file: .env
    # image: mariadb:10.7.8-focal
    #image: "mysql:${MYSQL_version}"
    image: "${IMAGE_DB}"

    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./db/${PATH_DATA_DB}:/var/lib/mysql:rw
      - ./db/script.sql:/docker-entrypoint-initdb.d/script.sql:ro
    restart: always
    networks:
      - fpay_network
  
  web:
    #image: "prestashop/prestashop:${Prestashop_version}-${PHP_version}-apache"
    image: "${IMAGE_ECOMMERCE}"

    container_name: "${CONTAINER_NAME_ECOMMERCE}"
    environment:
      - PS_LANGUAGE=es
      - PS_INSTALL_AUTO=${PS_INSTALL_AUTO}
      - PS_DEV_MODE=1
      - PS_DOMAIN=localhost:8080
      - ADMIN_MAIL=admin@admin.com
      - ADMIN_PASSWD=password
      - PS_FOLDER_ADMIN=adminop
      - PS_FOLDER_INSTALL=installop
      - PS_COUNTRY=cl
      - DB_NAME=prestashop
      - DB_SERVER=db_service
      - DB_PASSWD=admin
      - PS_ERASE_DB=0

      - WORDPRESS_DB_HOST=db_service
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=admin
      - WORDPRESS_DB_NAME=prestashop
    ports:
      - "8080:80"
    volumes:
      - ./${PATH_DATA_ECOMM}:/var/www/html/
      #- ./prestashop/log:/var/log:ro
    expose:
      - 8080
    links:
      - db_service:db_service
    depends_on:
      - db_service
    networks:
      - fpay_network
    # deploy:
    #   resources:
    #       limits:
    #         cpus: 0.50
    #         memory: 512M
    #       reservations:
    #         cpus: 0.25
    #         memory: 128M

networks:
  fpay_network:
    driver: bridge
